name: Q&A

on:
    pull_request_target:

defaults:
    run:
        shell: bash

jobs:
    call-qa:
        uses: specter-global/app-tmp-recipes/.github/workflows/callable-qa.yaml@main
        secrets:
            token: ${{ secrets.BOT_TOKEN }}
